version: '3'


volumes:
  db-data2:


services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register2'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db


  db:
    image: postgres
    volumes:
      - 'db-data2:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'